[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Esquema de particions amb dues particions d'app (OTA0/OTA1) de 1.9MB cadascuna
board_build.partitions = min_spiffs.csv
build_flags =
    ; Augmenta el buffer MQTT per als missatges OTA (URL + checksum)
    -DMQTT_MAX_PACKET_SIZE=512
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    claws/BH1750 @ ^1.3.0
    adafruit/Adafruit HTU21DF Library @ ^1.0.5
